Update scripts from isocpp/CppCoreGuidelines

diff --git a/scripts/Makefile b/scripts/Makefile
--- a/scripts/Makefile
+++ b/scripts/Makefile
@@ -17,11 +17,12 @@ all: \
 check-markdown \
 check-references \
 check-notabs \
+hunspell-check \
 cpplint-all \
 check-badchars
 
 $(BUILD_DIR):
-	mkdir -p $(BUILD_DIR)
+	@mkdir -p $(BUILD_DIR)
 
 #### clean: remove all files generated by the productive rules
 .PHONY: clean
@@ -39,6 +40,7 @@ distclean:
 ## run remark markdown checker based on configuration in .remarkrc
 .PHONY: check-markdown
 check-markdown: nodejs/node_modules/remark nodejs/remark/.remarkrc $(SOURCEPATH) $(BUILD_DIR) Makefile
+	echo '##################### Markdown check ##################'
 ## run remark, paste output to temporary file
 	cd nodejs; ./node_modules/.bin/remark ../$(SOURCEPATH) --no-color -q --config-path ./remark/.remarkrc 1> ../$(BUILD_DIR)/$(SOURCEFILE).fixed --frail
 
@@ -53,42 +55,58 @@ show-diff: nodejs/node_modules/remark nodejs/remark/.remarkrc $(SOURCEPATH) $(BU
 
 .PHONY: check-references
 check-references: $(SOURCEPATH) $(BUILD_DIR) Makefile
+	@echo '##################### References check ##################'
 ## check references unique
-	rm -f $(BUILD_DIR)/$(SOURCEFILE).uniq
-	grep -oP '(?<=<a name=")[^\"]+' $(SOURCEPATH) | uniq -d > $(BUILD_DIR)/$(SOURCEFILE).uniq
+	@rm -f $(BUILD_DIR)/$(SOURCEFILE).uniq
+	@grep -oP '(?<=<a name=")[^\"]+' $(SOURCEPATH) | sort | uniq -d > $(BUILD_DIR)/$(SOURCEFILE).uniq
 ## check if output has data
-	if [ -s "build/CppCoreGuidelines.md.uniq" ]; then echo 'Found duplicate anchors:'; cat $(BUILD_DIR)/$(SOURCEFILE).uniq; false; fi
+	@if [ -s "build/CppCoreGuidelines.md.uniq" ]; then echo 'Found duplicate anchors:'; cat $(BUILD_DIR)/$(SOURCEFILE).uniq; false; fi
 
 .PHONY: check-notabs
 check-notabs: $(SOURCEPATH) $(BUILD_DIR) Makefile
+	@echo '##################### Tabs check ##################'
 # find lines with tabs
 # old file still might be around
-	rm -f $(BUILD_DIR)/CppCoreGuidelines.md.tabs
+	@rm -f $(BUILD_DIR)/CppCoreGuidelines.md.tabs
 # print file, add line numbers, remove tabs from nl tool, grep for remaining tabs, replace with stars
-	cat ../CppCoreGuidelines.md | nl -ba | sed -s 's/\(^[^\t]*\)\t/\1--/g' | grep -P '\t' | sed -s 's/\t/\*\*\*\*/g' > $(BUILD_DIR)/CppCoreGuidelines.md.tabs
-	if [ -s $(BUILD_DIR)/CppCoreGuidelines.md.tabs ]; then echo 'Warning: Tabs found:'; cat $(BUILD_DIR)/CppCoreGuidelines.md.tabs; false; fi;
+	@cat ../CppCoreGuidelines.md | nl -ba | sed -s 's/\(^[^\t]*\)\t/\1--/g' | grep -P '\t' | sed -s 's/\t/\*\*\*\*/g' > $(BUILD_DIR)/CppCoreGuidelines.md.tabs
+	@if [ -s $(BUILD_DIR)/CppCoreGuidelines.md.tabs ]; then echo 'Warning: Tabs found:'; cat $(BUILD_DIR)/CppCoreGuidelines.md.tabs; false; fi;
 
 .PHONY: check-badchars
 check-badchars: $(SOURCEPATH) $(BUILD_DIR) Makefile
+	@echo '##################### Bad chars check ##################'
 # find lines with tabs
 # old file still might be around
-	rm -f $(BUILD_DIR)/CppCoreGuidelines.md.badchars
+	@rm -f $(BUILD_DIR)/CppCoreGuidelines.md.badchars
 # print file, add line numbers, grep for bad chars
-	cat ../CppCoreGuidelines.md | nl -ba | grep -P '’|‘|”|“|¸|–|…|¦' > $(BUILD_DIR)/CppCoreGuidelines.md.badchars || true
-	if [ -s $(BUILD_DIR)/CppCoreGuidelines.md.badchars ]; then echo 'Warning: Undesired chars (–’‘“”¸…¦) found, use straight quotes instead:'; cat $(BUILD_DIR)/CppCoreGuidelines.md.badchars; false; fi;
+	@cat ../CppCoreGuidelines.md | nl -ba | grep -P '’|‘|”|“|¸|–|…|¦' > $(BUILD_DIR)/CppCoreGuidelines.md.badchars || true
+	@if [ -s $(BUILD_DIR)/CppCoreGuidelines.md.badchars ]; then echo 'Warning: Undesired chars (–’‘“”¸…¦) found, use straight quotes instead:'; cat $(BUILD_DIR)/CppCoreGuidelines.md.badchars; false; fi;
 
 
+.PHONY: hunspell-check
+hunspell-check: $(BUILD_DIR)/plain-nohtml.txt
+	@echo '##################### Spell check ##################'
+	hunspell -p hunspell/isocpp.dic -u < build/plain-nohtml.txt > $(BUILD_DIR)/hunspell-report.txt
+	@if [ -s $(BUILD_DIR)/hunspell-report.txt ]; then echo 'Warning: Spellcheck failed, fix words or add to dictionary:'; cat $(BUILD_DIR)/hunspell-report.txt; false; fi;
+
+# only list words that are not in dict
+# to include all add them to bottom of hunspell/isocpp.dict, and run
+# cat hunspell/isocpp.dic | sort | uniq > hunspell/isocpp.dic2; mv hunspell/isocpp.dic2 hunspell/isocpp.dic
+.PHONY: hunspell-list
+hunspell-list: $(BUILD_DIR)/plain.txt
+	hunspell -p hunspell/isocpp.dic -l < build/plain-nohtml.txt
 
 #### Cpplint
 
 .PHONY: cpplint-all
 cpplint-all: $(BUILD_DIR)/codeblocks $(BUILD_DIR)/Makefile python/Makefile.in
+	@echo '##################### C++ Style check ##################'
 	cd $(BUILD_DIR)/codeblocks; $(MAKE) cpplint-all -k
 
 #### generic makefile for sourceblocks (need to be evaluated after c++ file generation)
 
 $(BUILD_DIR)/Makefile: python/Makefile.in
-	cp python/Makefile.in $(BUILD_DIR)/codeblocks/Makefile
+	@cp python/Makefile.in $(BUILD_DIR)/codeblocks/Makefile
 
 #### split md file into plain text and code
 
@@ -96,9 +114,12 @@ $(BUILD_DIR)/codeblocks: splitfile
 
 $(BUILD_DIR)/plain.txt: splitfile
 
+$(BUILD_DIR)/plain-nohtml.txt: $(BUILD_DIR)/plain.txt
+	sed 's;<a \(name\|href\)=".*</a>;;g' $(BUILD_DIR)/plain.txt > $(BUILD_DIR)/plain-nohtml.txt
+
 .PHONY: splitfile
 splitfile: $(SOURCEPATH) ./python/md-split.py
-	python ./python/md-split.py $(SOURCEPATH) $(BUILD_DIR)/plain.txt $(BUILD_DIR)/codeblocks
+	@python ./python/md-split.py $(SOURCEPATH) $(BUILD_DIR)/plain.txt $(BUILD_DIR)/codeblocks
 
 #### install npm modules
 # install/update npm dependencies defined in file package.json
